### ISSUE TITLE
TypeScript type definition file (I can add if you wish)

### ISSUE THREAD

**Issue by geopic** [ColinEspinas/darken#2]
**Is your feature request related to a problem? Please describe.**
Yes, when people use this package with TypeScript they will need to have type definitions in order to know which type of arguments / return value is expected.

**Describe the solution you'd like**
Developers using this package in their TypeScript projects being notified about the proper type of value passed in to this module.

**Describe alternatives you've considered**
N/A

**Additional context**
It helps keep developers' code type-safe.

Thank you.

**Comment by ColinEspinas** [comment]
Feel free to do it and to do a merge request. See the contributing guidelines for more details. Thanks for the help.

**Comment by geopic** [comment]
No worries Colin, I'll have it done by the end of the weekend :)
