### ISSUE TITLE
Timestamps based mode switch

### ISSUE THREAD

**Issue by ColinEspinas** [ColinEspinas/darken#6]
**Is your feature request related to a problem? Please describe.**
Yes, when a user come to an app/website to a fixed hour it will be cool to change the theme depending on the time.

**Describe the solution you'd like**
The option can take timestamps as an input to switch modes.

Exemple of implementation : 
```javascript
const darkmode = new darken({
	class: "darkmode-active",
	timestamps: {
		dark: "20:00",
		light: "6:00",
	}
	variables: {
		"--primary-color" : ["#000000", "#fafafa"],
		"--background-color" : ["#fafafa", "#000000"]
	},
});
```

**Comment by germangamboa95** [comment]
If https://developer.mozilla.org/en-US/docs/Web/API/Ambient_Light_Events ever becomes a mainstream thing it would be cool if this ran off that.

**Comment by ColinEspinas** [comment]
Yes @germangamboa95 that can be cool but I think that it is another feature, would be better to do a separate issue on the subject if you want to.
