### ISSUE TITLE
Uncaught TypeError: Cannot read property 'addEventListener'

### ISSUE THREAD

**Issue by isaacdarcilla** [ColinEspinas/darken#8]
There is a return error ```Uncaught: TypeError```

```js
Uncaught TypeError: Cannot read property 'addEventListener' of null
    at new e (darken.umd.js:1)
    at event:26
```
**Screenshots**
<img src="hhttps://i.postimg.cc/nVR8w0jB/Deepin-Screenshot-select-area-20200309192606.png"> 
<img src="https://i.postimg.cc/hjMFn0CF/Deepin-Screenshot-select-area-20200309193503.png">

The error causes the toggle to not function.

**Desktop**
 - OS: Deepin Linux
 - Browser: Chrome
 - Version: Version 78.0.3904.97 (Official Build) (64-bit)

**Comment by ColinEspinas** [comment]
What version of darken are you using ?

**Comment by ColinEspinas** [comment]
This problem may be due to an incorrect `container` selector, this selector uses [`querySelector`](https://developer.mozilla.org/fr/docs/Web/API/Document/querySelector) so you need to give a valid CSS query selector. 

I will suppose that this problem is solved because there is no response.
